### ISSUE TITLE
Issue w/ Backdoor Adjustment Notebook

### ISSUE THREAD

**Issue by agrawalraj** [BasisResearch/chirho#257]
In the backdoor adjustment notebook, 

```
class BayesianBackdoorSATE(pyro.nn.PyroModule):

    def __init__(self, causal_model: BayesianBackdoor):
        super().__init__()
        self.conditioned_model = ConditionedBayesianBackdoor(causal_model)

    def forward(self, covariates_obs, training_obs, earnings_obs):

        # Sample jointly from observational and counterfactual distributions
        with MultiWorldCounterfactual(), do(actions={"training": 1. - training_obs}):
            _, _, earnings = self.conditioned_model(covariates_obs, training_obs, earnings_obs)

            # Evaluate the sample average treatment effect
            earnings_cf = gather(earnings, IndexSet(training={1}))
            earnings_f = gather(earnings, IndexSet(training={0}))
            ites = torch.where(training_obs == 1, earnings_cf - earnings_f, earnings_f - earnings_cf)
            return pyro.deterministic("SATE", torch.mean(ites, dim=-1, keepdim=True), event_dim=0)
```

Here ites should be replaced to `ites = torch.where(training_obs == 0, earnings_cf - earnings_f, earnings_f - earnings_cf)`. But in that case the estimated effect is negative. We should look through the model & data code to see what's going on, and make modifications to the model if needed.

**Comment by eb8680** [comment]
I looked into this, and the source of the problem was performing joint inference and imputation in a single stage of approximate inference. The dataset is tiny and the model is necessarily highly misspecified, so when you don't do that, it works much better - the resulting ATE estimates and uncertainties are actually closer to the improved estimates using matching in the original blog post:

![image](https://github.com/BasisResearch/chirho/assets/2032320/7b3126d8-5a7f-46f7-8825-c8a1c25c21bc)
