### ISSUE TITLE
TypeError: 'function' object is not subscriptable when running example

### ISSUE THREAD

**Issue by diro5t** [BasisResearch/chirho#537]
Hi,

when I try to run the following example, I get this error:

![image](https://github.com/BasisResearch/chirho/assets/57329722/44b309b3-9ca9-4ff3-a381-4e7742f8318c)

Am I doing sth. wrong?

Thanks

**Comment by SamWitty** [comment]
Thanks for your interest in ChiRho!

I believe this error is because of incompatible versions of Pyro 1.9.0 and ChiRho 0.2.0, which has been addressed in `master` at https://github.com/BasisResearch/chirho/commit/90675c0366aa85d8819f13bda759aa2e0c2e6423 but hasn't made its way into a release. Could you please share which versions of Pyro and ChiRho you're using? If Pyro > 1.8.6, downgrading to 1.8.6 should fix the issue.

**Comment by diro5t** [comment]
Thanks for letting me know. Are updates planned, which are compatible with Pyro 1.9.0?

**Comment by SamWitty** [comment]
Yes, we'll be releasing another version soon that is compatible with Pyro 1.9.0. See https://github.com/BasisResearch/chirho/pull/521 and https://github.com/BasisResearch/chirho/pull/527.

Did my suggestion of downgradind Pyro to 1.8.6 work?

**Comment by diro5t** [comment]
Hi Sam, yep thanks - worked like a charm!
